// pages/index.vue
<template>
  <div class="wrapper">
    <h1>都道府県別の総人口推移グラフ</h1>
    <AppPrefectures :prefectures="prefectures" @check="fetchPopulationComposition" @uncheck="removeTotalPopulation" />
    <AppChart :total-population="totalPopulation" />
  </div>
</template>

<script>
import AppPrefectures from '~/components/AppPrefectures.vue';
import AppChart from '~/components/AppChart.vue';

export default {
  components: {
    AppPrefectures,
    AppChart
  },

  data() {
    return {
      prefectures: [],
      totalPopulation: []
    };
  },

  async asyncData({ app }) {
    const { result } = await app.$axios
      .$get('/prefectures', {
        headers: {
          'X-API-KEY': process.env.RESAS_API_KEY
        }
      });

    return { prefectures: result };
  },

  methods: {
    async fetchPopulationComposition({ prefName, prefCode }) {
      const { result } = await this.$axios.$get(`/population/composition/perYear?prefCode=${prefCode}`, {
        headers: {
         'X-API-KEY': process.env.RESAS_API_KEY
        }
      });

      const totalPopulation = result.data[0];

      this.totalPopulation = [...this.totalPopulation, {
        prefName,
        prefCode,
        data: totalPopulation.data
      }];
    },

    removeTotalPopulation(prefCode) {
      const index = this.totalPopulation.findIndex(population => {
        return population.prefCode === prefCode;
      });

      this.totalPopulation.splice(index, 1);
    },
  }
};
</script>

<style>
.wrapper {
  padding: 32px;
}

h1 {
  font-size: 32px;
  margin-bottom: 24px;
  text-align: center;
}
</style>

// pages/index.tsx
import { useState, useEffect } from 'react';
import fetch from 'node-fetch';
import styled from '@emotion/styled';
import AppPrefectures from '../components/AppPrefectures';
import AppChart from '../components/AppChart';
import { Prefecture } from '../interfaces';

const Wrapper = styled.div`
  padding: 32px;
`;

const H1 = styled.h1`
  margin-bottom: 24px;
  font-size: 32px;
  text-align: center;
`;

type Props = {
  result: Prefecture[]
};

const Home: React.FC<Props> = ({ result }) => {
  const [totalPopulation, setTotalPopulation] = useState([]);

  const fetchPopulationComposition = async ({ prefName, prefCode }) => {
    const res = await fetch(
      `https://opendata.resas-portal.go.jp/api/v1/population/composition/perYear?prefCode=${prefCode}`,
      {
        headers: {
          'X-API-KEY': process.env.RESAS_API_KEY
        }
      }
    );
    const { result } = await res.json();
    const newTotalPopulation = result.data[0];

    setTotalPopulation([...totalPopulation, {
      prefName,
      prefCode,
      data: newTotalPopulation.data
    }]);
  };

  const removeTotalPopulation = (prefCode) => {
    const index = totalPopulation.findIndex(population => {
      return population.prefCode === prefCode;
    });
    const newTotalPopulation = [...totalPopulation];

    newTotalPopulation.splice(index, 1);
    setTotalPopulation(newTotalPopulation);
  };

  return (
    <Wrapper>
      <H1>都道府県別の総人口推移グラフ</H1>
      <AppPrefectures prefectures={result} fetchPopulationComposition={fetchPopulationComposition} removeTotalPopulation={removeTotalPopulation} />
      <AppChart totalPopulation={totalPopulation} useEffect={useEffect} />
    </Wrapper>
  );
};

export async function getStaticProps() {
  const res = await fetch(
    'https://opendata.resas-portal.go.jp/api/v1/prefectures',
    {
      headers: {
        'X-API-KEY': process.env.RESAS_API_KEY
      }
    }
  );
  const { result } = await res.json();

  return {
    props: {
      result
    }
  };
}

export default Home;
